jobs: 
  build:
    image: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.1
      - run: dotnet build

  test:
  analyze:
  package:
  deploy:







# person: #object
#   firstName: 'string' #string
#   lastName: 100 #number
#   middleName: true #boolean
#   alias: #collection
#     - 'dotnet'
#     - 'lead'
#     - subAlias: