jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.1
      - run: dotnet build

  test:
    # needs: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.1
      - run: dotnet test -p:CollectCoverage=true

  analyze:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.1
      - run: dotnet tool install --global dotnet-sonarscanner --version 4.10.0
      - run: |
          dotnet sonarscanner begin
          dotnet build
          dotnet test -p:CollectCoverage=true
          dotnet sonarscanner end

name: cibuild

on: push

# package:
# deploy:

# for selecting specific branch
# on:
#   push:
#     branches:
#       - master

# person: #object
#   firstName: 'string' #string
#   lastName: 100 #number
#   middleName: true #boolean
#   alias: #collection
#     - 'dotnet'
#     - 'lead'
#     - subAlias:
